#!/bin/bash -e

rm -rf ${ADIOS2_BUILD_DIR} ${ADIOS2_INSTALL_DIR}
mkdir -p ${ADIOS2_BUILD_DIR}
cd ${ADIOS2_BUILD_DIR}

OPTIONS=(
-D CMAKE_BUILD_TYPE=Release
-D CMAKE_INSTALL_PREFIX="${ADIOS2_INSTALL_DIR}"
-D CMAKE_CXX_COMPILER=${MYCXX}
-D CMAKE_C_COMPILER=${MYCC}
-D CMAKE_Fortran_COMPILER=${MYFTN}
)
cmake "${OPTIONS[@]}" "${ADIOS2_SOURCE_DIR:-../}"
make -j -l32
make install

#-D CMAKE_CXX_STANDARD=14
#-D CMAKE_CXX_FLAGS=-std=c++14
#-D CMAKE_CXX_FLAGS=-std=c++14