#!/bin/bash -e

rm -rf ${CAMTIMERS_BUILD_DIR} ${CAMTIMERS_INSTALL_DIR}
mkdir ${CAMTIMERS_BUILD_DIR}
cd ${CAMTIMERS_BUILD_DIR}

OPTIONS=(
-D CMAKE_BUILD_TYPE=Release
-D CMAKE_INSTALL_PREFIX=${CAMTIMERS_INSTALL_DIR}
-D CMAKE_C_COMPILER=clang
-D CMAKE_Fortran_COMPILER=flang
-D CAMTIMERS_USE_MPI=FALSE
)

cmake "${OPTIONS[@]}" "${CAMTIMERS_SOURCE_DIR:-../}"
make -j -l32
make install
