#!/bin/bash -e

CAMTIMERS_BUILD_DIR=${CAMTIMERS_BUILD_DIR}_mpi
CAMTIMERS_INSTALL_DIR=${CAMTIMERS_INSTALL_DIR}_mpi
rm -rf ${CAMTIMERS_BUILD_DIR} ${CAMTIMERS_INSTALL_DIR}
mkdir ${CAMTIMERS_BUILD_DIR}
cd ${CAMTIMERS_BUILD_DIR}

OPTIONS=(
-D CMAKE_BUILD_TYPE=Release
-D CMAKE_INSTALL_PREFIX=${CAMTIMERS_INSTALL_DIR}
-D CMAKE_C_COMPILER=${MYCC}
-D CMAKE_Fortran_COMPILER=${MYFTN}
-D CAMTIMERS_USE_MPI=TRUE
)

cmake "${OPTIONS[@]}" "${CAMTIMERS_SOURCE_DIR:-../}"
make -j -l32
make install
