#!/bin/bash -e

rm -rf ${KOKKOS_BUILD_DIR} ${KOKKOS_INSTALL_DIR}
mkdir -p ${KOKKOS_BUILD_DIR}
cd ${KOKKOS_BUILD_DIR}

OPTIONS=(
-D CMAKE_BUILD_TYPE=Release
-D CMAKE_INSTALL_PREFIX="${KOKKOS_INSTALL_DIR}"
-D CMAKE_CXX_COMPILER=${MYCXX}
-D Kokkos_ENABLE_OPENMP=ON
-D Kokkos_ENABLE_SERIAL=ON
-D Kokkos_ENABLE_HIP=ON
-D Kokkos_ARCH_ZEN2=ON
-D Kokkos_ARCH_VEGA908=ON
-D Kokkos_ENABLE_AGGRESSIVE_VECTORIZATION=ON
-D Kokkos_ENABLE_TESTS=OFF
-D BUILD_TESTING=OFF
)
cmake "${OPTIONS[@]}" "${KOKKOS_SOURCE_DIR:-../}"
make -j -l32
make install

#-D CMAKE_CXX_STANDARD=14
#-D CMAKE_CXX_FLAGS=-std=c++14
#-D CMAKE_CXX_FLAGS=-std=c++14